CREATE TABLE aduanas (
  adua INTEGER PRIMARY KEY,
  name VARCHAR(255)
);

INSERT INTO aduanas (adua, name) VALUES
(00, 'Nivel Central'),
(01, 'Dirección Seccional de Impuestos y Aduanas de Armenia'),
(02, 'Dirección Seccional de Impuestos de Barranquilla'),
(03, 'Dirección Seccional de Aduanas de Bogotá – Aeropuerto El Dorado'),
(04, 'Dirección Seccional de Impuestos y Aduanas de Bucaramanga'),
(05, 'Dirección Seccional de Impuestos de Cali'),
(06, 'Dirección Seccional de Impuestos de Cartagena'),
(07, 'Dirección Seccional de Impuestos de Cúcuta'),
(08, 'Dirección Seccional de Impuestos y Aduanas de Girardot'),
(09, 'Dirección Seccional de Impuestos y Aduanas de Ibagué'),
(10, 'Dirección Seccional de Impuestos y Aduanas de Manizales'),
(11, 'Dirección Seccional de Impuestos de Medellín'),
(12, 'Dirección Seccional de Impuestos y Aduanas de Montería'),
(13, 'Dirección Seccional de Impuestos y Aduanas de Neiva'),
(14, 'Dirección Seccional de Impuestos y Aduanas de Pasto'),
(15, 'Dirección Seccional de Impuestos y Aduanas de Palmira'),
(16, 'Dirección Seccional de Impuestos y Aduanas de Pereira'),
(17, 'Dirección Seccional de Impuestos y Aduanas de Popayán'),
(18, 'Dirección Seccional de Impuestos y Aduanas de Quibdó'),
(19, 'Dirección Seccional de Impuestos y Aduanas de Santa Marta'),
(20, 'Dirección Seccional de Impuestos y Aduanas de Tunja'),
(21, 'Dirección Seccional de Impuestos y Aduanas de Tuluá'),
(22, 'Dirección Seccional de Impuestos y Aduanas de Villavicencio'),
(23, 'Dirección Seccional de Impuestos y Aduanas de Sincelejo'),
(24, 'Dirección Seccional de Impuestos y Aduanas de Valledupar'),
(25, 'Dirección Seccional de Impuestos y Aduanas de Riohacha'),
(26, 'Dirección Seccional de Impuestos y Aduanas de Sogamoso'),
(27, 'Dirección Seccional de Impuestos y Aduanas de San Andrés'),
(28, 'Dirección Seccional de Impuestos y Aduanas de Florencia'),
(29, 'Dirección Seccional de Impuestos y Aduanas de Barrancabermeja'),
(31, 'Dirección Operativa de Grandes Contribuyentes'),
(32, 'Dirección Seccional de Impuestos de Bogotá'),
(34, 'Dirección Seccional de Impuestos y Aduanas de Arauca'),
(35, 'Dirección Seccional de Impuestos y Aduanas de Buenaventura'),
(37, 'Dirección Seccional de Impuestos y Aduanas de Ipiales'),
(38, 'Dirección Seccional de Impuestos y Aduanas de Leticia'),
(39, 'Dirección Seccional de Impuestos y Aduanas de Maicao'),
(40, 'Dirección Seccional de Impuestos y Aduanas de Tumaco'),
(41, 'Dirección Seccional de Impuestos y Aduanas de Urabá'),
(42, 'Dirección Seccional Delegada de Impuestos y Aduanas de Puerto Carreño'),
(43, 'Dirección Seccional Delegada de Impuestos y Aduanas de Puerto Inírida'),
(44, 'Dirección Seccional de Impuestos y Aduanas de Yopal'),
(45, 'Dirección Seccional Delegada de Impuestos y Aduanas Mitú'),
(46, 'Dirección Seccional de Impuestos y Aduanas de Puerto Asís'),
(48, 'Dirección Seccional de Aduanas de Cartagena'),
(78, 'Dirección Seccional Delegada de Impuestos y Aduanas de San José de Guaviare'),
(86, 'Dirección Seccional Delegada de Impuestos y Aduanas de Pamplona'),
(87, 'Dirección Seccional de Aduanas de Barranquilla'),
(88, 'Dirección Seccional de Aduanas de Cali'),
(89, 'Dirección Seccional de Aduanas de Cúcuta'),
(90, 'Dirección Seccional de Aduanas de Medellín'),
(91, 'Dirección Seccional de Aduanas de Bogotá');